### ISSUE TITLE
standardize the status strings

### ISSUE THREAD

**Issue by steveloranz** [redhat-imaging/imagefactory#191]
instead of repeating the same status string everywhere, we should be pulling from a constant to avoid typos and to discourage each plugin from defining its own status strings.

Right now there are cases of COMPLETE vs COMPLETED and there is a list of status strings in PersistentImage that do not reflect what is actually being set in the plugins.

**Comment by imcleod** [comment]
Closing as part of a general cleanup of very stale issues that are either WONTFIX or no longer relevant.
