### ISSUE TITLE
Update Rackspace plugin

### ISSUE THREAD

**Issue by dkliban** [redhat-imaging/imagefactory#237]
The plugin for Rackspace does not work at this time.  The current implementation uses a deprecated rackspace library.  Need to replace with new version.

**Comment by imcleod** [comment]
This should be addressed with the move to "pyrax" and the addition of pyrax to Fedora.  More recently, a Rackspace employee has been added as a maintainer for pyrax.

Commit that enabled this: e49af5b81e21ab6086932313b96315a90c2f1a6c
