### ISSUE TITLE
ImageFactoryException "OS plugin does not support distro (Fedora) update (17) in TDL" thrown instead of actual exception

### ISSUE THREAD

**Issue by dkliban** [redhat-imaging/imagefactory#253]
The real exception is swallowed because of generic except on line 322: https://github.com/aeolusproject/imagefactory/blob/master/imagefactory-plugins/FedoraOS/FedoraOS.py#L322

I had it thrown cause of FedoraOS plugin dependencies missing. Also when OzException('Could not find a viable libvirt NAT bridge, install cannot continue',).

**Comment by imcleod** [comment]
Current upstream now detects non-running libvirtd and throws a more helpful exception.
