### ISSUE TITLE
Package latest version of python-psphere for Fedora.

### ISSUE THREAD

**Issue by dkliban** [redhat-imaging/imagefactory#284]
vSphere plugin requires python-psphere 0.5.2.  Fedora repositories currently house 0.1.4.  Need to make 0.5.2 available for Fedora.

**Comment by tflink** [comment]
python-psphere 0.5.2 is available for F21+,  I assume this can be closed?

**Comment by imcleod** [comment]
I agree with tflink - This can be closed :-)
