### ISSUE TITLE
qemu is unable to access the libguestfs snap files created in /tmp

### ISSUE THREAD

**Issue by gfidente** [redhat-imaging/imagefactory#286]
when imagefactoryd runs as root, libguestfs process creates its temporary files in /tmp as root too

libvirtd instead, by default, spawns the qemu process as qemu resulting in a permission denied error like:

> RuntimeError: could not create appliance through libvirt: internal error process exited while connecting to monitor: qemu-kvm: -drive file=/tmp/libguestfsJLnXYN/snapshot1,if=none,id=drive-scsi0-0-1-0,format=qcow2,cache=unsafe: could not open disk image /tmp/libguestfsJLnXYN/snapshot1: Permission denied

**Comment by imcleod** [comment]
I believe this has sorted itself out at some point.  I regularly run Factory as root with libvirt being used as the backing management for libguestfs.
