### ISSUE TITLE
Make Nova plugin feature complete

### ISSUE THREAD

**Issue by steveloranz** [redhat-imaging/imagefactory#333]
@imcleod points out that the current base image is not feature complete with those created by the TinMan plugin as it does not perform all of the customizations outside of the OS section of the TDL. 

In addition, the target customizations delegated by the cloud plugins need to be handled.

**Comment by imcleod** [comment]
The Nova plugin is effectively deprecated.  Closing WONTFIX for the time being.  If there's genuine interest in reviving Nova support please reopen.
