### ISSUE TITLE
ovf_memory_mb is not setting the RAM of the Vagrant box image

### ISSUE THREAD

**Issue by LalatenduMohanty** [redhat-imaging/imagefactory#356]
I am using http://cbs.centos.org/koji/ to build Vagrant boxes. However the default RAM in the boxes is 512MB and to crease the RAM to 1GB , I have used  "  --ova-option ovf_memory_mb=1024" but it did not result in increase of RAM in the box.  The command I ran is as below. 

The scratch build is available at : https://cbs.centos.org/koji/taskinfo?taskID=16838

```
koji -p cbs image-build \
  centos-7-atomicapp 1  bananas7-el7 \
  http://mirror.centos.org/centos/7/os/x86_64/ x86_64 \
  --release=1 \
  --distro RHEL-7.0 \
  --ksver RHEL7 \
  --kickstart=./build_tools/kickstarts/centos-7-kubernetes-vagrant.ks \
  --format=qcow2 \
  --format=vsphere-ova \
  --format=rhevm-ova \
  --ova-option vsphere_ova_format=vagrant-virtualbox \
  --ova-option rhevm_ova_format=vagrant-libvirt \
  --ova-option vagrant_sync_directory=/vagrant \
  --ova-option ovf_memory_mb=1024 \
  --repo http://mirror.centos.org/centos/7/extras/x86_64/\
  --repo http://mirror.centos.org/centos/7/updates/x86_64/\
  --scratch \
  --nowait \
  --disk-size=20
```

**Comment by LalatenduMohanty** [comment]
CC @imcleod

**Comment by imcleod** [comment]
Mr. Mohanty,

Thank you for your interest in Image Factory.  Can you please clarify which Vagrant provider you are observing this behaviour on?

The OVA options can only propagate to Virtualbox guests.  If you are using vagrant-libvirt, the memory options are not actually carried into the Vagrant box.

Note that you can set these values in the Vagrantfile for vagrant-libvirt as documented here:

https://github.com/pradels/vagrant-libvirt#domain-specific-options

**Comment by LalatenduMohanty** [comment]
@imcleod I think I was using the vagrant-libvirt . Thanks for the info :)
