### ISSUE TITLE
raw image download endpoint in REST api does not work

### ISSUE THREAD

**Issue by tflink** [redhat-imaging/imagefactory#360]
Attempting to download a raw image through the REST api using a GET request to the `/imagefactory/base_image/<image_id>/raw_image` endpoint results in an HTTP 500 and the following error in imagefactoryd.log:

```
2015-11-05 14:45:31,255 ERROR imgfac.rest.RESTv2 thread(worker 5) Message: 'raw_image'
Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/imgfac/rest/RESTv2.py", line 65, in list_images
    _type = IMAGE_TYPES[image_collection]
KeyError: 'raw_image'
```

It appears as if the request isn't being routed to the desired raw_image handler (`imgfac.rest.RESTv2.get_image_file`) but to the image listing handler (`imgfac.rest.RESTv2.list_images`) using the `/imagefactory/base_images/<base_image_id>/<image_collection>` route.

Either fix the bottle setup so that the `base_image/<image_id>/raw_image` endpoint works or create a new endpoint which does not collide with `list_images()`

**Comment by tflink** [comment]
Any thoughts on a desired way to solve this? I see two options: explicitly define routing or change the endpoint for downloading raw_image.

My first thought would be to change the url scheme to something like `/imagefactory/download/base_image` because that's a simple solution - it does fracture the api a bit but it's a simpler solution in my mind.

Any thoughts on these options (especially from folks who would be reviewing a PR)?

**Comment by imcleod** [comment]
Fix merged: https://github.com/redhat-imaging/imagefactory/commit/d9a7fbfb28f89f33a5367c9426873b725d1b9ad4

Many thanks!
