### ISSUE TITLE
VMWare: Hardcoded LSI disk controller

### ISSUE THREAD

**Issue by cgwalters** [redhat-imaging/imagefactory#372]
Besides higher performance, the paravirt controller supports hot-adding disks.  See https://kb.vmware.com/selfservice/microsites/search.do?language=en_US&cmd=displayKC&externalId=1010398

I think we need a way to make this configurable - in theory someone could be producing an OS image without the paravirt drivers.

**Comment by imcleod** [comment]
Added here and configurable via "parameter" switches:

https://github.com/redhat-imaging/imagefactory/commit/115509e069c28349ed870faedf67390363f39531
