### ISSUE TITLE
Docker plugin using threading isAlive() py2 method

### ISSUE THREAD

**Issue by hruskape** [redhat-imaging/imagefactory#441]
threading.Tread isAlive() method is not available in python3 anymore. Should be changed to is_alive(). This would be backward compatible with python2.7.

Now with python3 we are getting error 

kojid[28238]: xmlrpc.client.Fault: <Fault 1018: "Image status is FAILED: 'Thread' object has no attribute 'isAlive'">

```
--- /usr/lib/python3.9/site-packages/imagefactory_plugins/Docker/Docker.py.orig 2020-11-24 10:03:42.910369722 +0200
+++ /usr/lib/python3.9/site-packages/imagefactory_plugins/Docker/Docker.py      2020-11-24 10:04:01.913238924 +0200
@@ -376,7 +376,7 @@ class Docker(object):
                     self.log.error("WARNING: Could not unmount guest at (%s) - may still be mounted" % (tempdir) )
             if fuse_thread:
                 fuse_thread.join(30.0)
-                if fuse_thread.isAlive():
+                if fuse_thread.is_alive():
                     self.log.error("Guestfs local mount thread is still active - FUSE filesystem still mounted at (%s)" % (tempdir) )
 
         if wrap_metadata:
```

**Comment by mnk** [comment]
+1 
There is a couple of places where the isAlive method is used: https://github.com/redhat-imaging/imagefactory/pull/442
I have created a bug report on Fedora 33: https://bugzilla.redhat.com/show_bug.cgi?id=1904804

**Comment by breillyr** [comment]
Thanks, filed a PR for the change.

**Comment by breillyr** [comment]
Sorry, missed your PR you filed already @mnk, will merge that instead.

**Comment by breillyr** [comment]
https://github.com/redhat-imaging/imagefactory/pull/442 fixes this issue.
